import streamlit as st
import requests
import datetime
import sys

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="AI Vacation Itinerary Planner",
    page_icon=":airplane:",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("Vacation Planner Agentic Application")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Planning a vacation? Where do you want to go?")

with st.form(key="query_form", clear_on_submit = True):
    user_input = st.text_input("User Input",placeholder="E.g., Plan a 5-day trip to Paris in September with a budget of $2000.")
    submit_button=st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Planning your vacation..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer provided.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** XYZ's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"